# Generated by Django 5.2.8 on 2025-11-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('anno', models.IntegerField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('immaginePrincipale', models.ImageField(blank=True, null=True, upload_to='opere/')),
            ],
        ),
        migrations.CreateModel(
            name='ImmagineOpera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='immaginiOpere/')),
                ('opera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='sitoArte.opera')),
            ],
        ),
        migrations.CreateModel(
            name='VideoOpera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videoOpere/')),
                ('opera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='sitoArte.opera')),
            ],
        ),
    ]
