# Generated by Django 5.2.8 on 2026-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitoArte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('luogo', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-data_inizio'],
            },
        ),
    ]
