# Generated by Django 5.2.8 on 2026-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitoArte', '0003_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografia',
            name='competenze',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biografia',
            name='esperienza',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biografia',
            name='obiettivi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
