# Generated by Django 5.2.8 on 2026-05-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitoArte', '0004_biografia_competenze_biografia_esperienza_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biografia',
            old_name='cv',
            new_name='curriculum',
        ),
    ]
