# Generated by Django 5.2.8 on 2026-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitoArte', '0005_rename_cv_biografia_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostra',
            name='luogo_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
