# Generated by Django 5.2.8 on 2026-05-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitoArte', '0006_mostra_luogo_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostra',
            name='luogo_addr',
        ),
        migrations.AddField(
            model_name='mostra',
            name='sito_luogo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
