# Generated by Django 5.2.8 on 2026-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitoArte', '0007_remove_mostra_luogo_addr_mostra_sito_luogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostra',
            name='mappa_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
